# Generated by Django 6.0.3 on 2026-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
